services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/var/app
    links:
      - postgres
    env_file:
      - .env
    networks:
      main:
        aliases:
          - api

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 120s
      timeout: 5s
      retries: 5
    networks:
      main:
        aliases:
          - postgres

networks:
  main:
    driver: bridge

volumes:
  postgres_data:
